14-Jun-2023 15:22:04 logging_module.py: This is a log message
14-Jun-2023 15:29:03 logging_module.py: This is a log message
14-Jun-2023 15:29:03 logging_module.py: low level issues
14-Jun-2023 15:29:03 logging_module.py: throw errors
14-Jun-2023 15:29:03 logging_module.py: log critical messages
14-Jun-2023 15:39:13 logging_module.py: This is a log message
14-Jun-2023 15:39:13 logging_module.py: low level issues
14-Jun-2023 15:39:13 logging_module.py: throw errors
14-Jun-2023 15:39:13 logging_module.py: log critical messages
14-Jun-2023 15:39:13 logging_module.py: test info level with handler
14-Jun-2023 15:39:13 logging_module.py: test warning level with handler
14-Jun-2023 15:45:57 logging_module.py: This is a log message
14-Jun-2023 15:45:57 logging_module.py: low level issues
14-Jun-2023 15:45:57 logging_module.py: throw errors
14-Jun-2023 15:45:57 logging_module.py: log critical messages
14-Jun-2023 15:45:57 logging_module.py: test info level with handler
14-Jun-2023 15:45:57 logging_module.py: test warning level with handler
14-Jun-2023 15:46:14 logging_module.py: This is a log message
14-Jun-2023 15:46:14 logging_module.py: low level issues
14-Jun-2023 15:46:14 logging_module.py: throw errors
14-Jun-2023 15:46:14 logging_module.py: log critical messages
14-Jun-2023 15:46:14 logging_module.py: test info level with handler
14-Jun-2023 15:46:14 logging_module.py: test warning level with handler
14-Jun-2023 15:46:14 logging_module.py: exception occurred
Traceback (most recent call last):
  File "c:\MyWorkSpace\MEDTRONICS\PIS System Sample Codes\Logging\logging_module.py", line 59, in <module>
    print(vals[4])
          ~~~~^^^
IndexError: list index out of range
